// Package actor implements the MarketActor — the single goroutine that owns
// one OrderBook and drives the chaos+replay pipeline.
//
// Design invariant (CRITICAL):
//
//	The MarketActor MUST be the ONLY writer to its OrderBook.
//	All external callers (CLI, HTTP handlers) submit orders via the OrderQueue
//	channel. The actor processes them on its goroutine, so no mutex is needed
//	inside OrderBook or Account.
//
// Event log guarantee:
//
//	Every event emitted is appended to the EventSink in sequence-number order.
//	Two runs with identical (seed, replay data) MUST produce byte-identical
//	output to the EventSink. This is tested by the determinism regression test.
//
// v0.4 — Chaos & Liquidation pipeline (per tick, in order):
//   1. emit TickAdvance
//   2. ApplyWick (if this TS is a kline OpenTS): inject a chaos sell order
//   3. Inject replay orders (limit → rest, market → match)
//   4. Drain user-order queue
//   5. Update mark price (chaos.MarkPrice with oracle lag)
//   6. Mark-to-market all accounts
//   7. Liquidation scan: any position with marginRatio ≤ MMR is force-closed
//   8. Funding settlement (every 8h of simulated time)
//   9. Build snapshot, apply depth shrink, emit
//   10. (Optional) Strict-invariant self-check
package actor

import (
	"context"
	"encoding/json"
	"fmt"
	"sort"

	"github.com/sandswind/perpCS/internal/account"
	"github.com/sandswind/perpCS/internal/chaos"
	"github.com/sandswind/perpCS/internal/orderbook"
	"github.com/sandswind/perpCS/internal/types"
)

// EventSink receives every event produced by the actor.
type EventSink interface {
	Emit(e types.Event) error
}

// FundingPoint is one historical funding-rate observation. Mirrors
// provider.FundingPoint (avoid import cycle by re-declaring here).
type FundingPoint struct {
	TS   int64   // chaos clock ns
	Rate float64 // e.g. 0.0001 = 1 bps (long pays short when positive)
}

// FundingIntervalNS is the simulated time between funding settlements.
const FundingIntervalNS = int64(8 * 60 * 60 * 1_000_000_000) // 8h

// DefaultInsuranceFund is the starting balance of the insurance fund (USDR scaled).
var DefaultInsuranceFund = types.QtyFromFloat(100_000)

// UserOrder is a user-submitted order envelope.
// The caller must send this into Config.OrderQueue and wait on ResultCh.
// For a cancel operation, set CancelOrderID to the target order ID and
// leave Order nil (or set it to a zero-value Order).
type UserOrder struct {
	Order         *types.Order
	CancelOrderID types.OrderID        // non-zero → cancel this order instead of placing
	ResultCh      chan UserOrderResult // buffered(1); caller blocks on receive
}

// UserOrderResult is sent back on UserOrder.ResultCh after the actor processes it.
type UserOrderResult struct {
	Trades []types.Trade
	Err    error
}

// Config holds the parameters for one MarketActor session.
type Config struct {
	Symbol      types.Symbol
	SessionID   string
	LevelID     string // e.g. "D-312-BTC"
	ChaosConfig chaos.Config
	// ReplayOrders is the pre-sorted slice of orders to inject, generated by
	// provider.KlinesToSynthOrders. Must be sorted by TS ascending.
	ReplayOrders []*types.Order
	// Klines (optional) drives wick injection — wicks fire only on kline
	// boundaries (OpenTS). If empty, wicks are disabled.
	Klines []types.Kline
	// FundingRates (optional) is the historical funding rate stream used for
	// 8h funding settlements. If empty, the actor falls back to DefaultFundingRate.
	FundingRates []FundingPoint
	// Sink receives every event. Must not be nil.
	Sink EventSink
	// OrderQueue delivers user orders to the actor goroutine.
	// If nil, the actor runs in replay-only mode (no user interaction).
	OrderQueue <-chan *UserOrder
	// InitialBalance is the player's starting balance (1e8 USDR scaled).
	// If 0 the account is not created (replay-only mode).
	InitialBalance types.Qty
	// PlayerAddress is used as the account owner ID.
	PlayerAddress string
	// InsuranceFund (optional) overrides the initial insurance fund.
	// Default DefaultInsuranceFund (100,000 USDR) when zero.
	InsuranceFund types.Qty
	// StrictInvariants enables panic-on-violation invariant checks (TEST MODE).
	StrictInvariants bool
}

// DefaultFundingRate is used when no historical rate matches the tick.
// 1 bps every 8h ≈ 11% APR — modest enough to not dominate trading PnL.
const DefaultFundingRate = 0.0001

// Actor is a single-goroutine market actor for one symbol.
// Run() drives the full replay loop and blocks until completion or ctx done.
type Actor struct {
	cfg        Config
	book       *orderbook.Book
	chaos      *chaos.Engine
	seq        uint64
	orders     []*types.Order // replay orders
	accounts   map[string]*account.Account
	nextUserID uint64 // monotonic user order ID counter (separate from book counter)

	// v0.4 — kline lookup for wick injection
	klineByTS map[int64]types.Kline

	// v0.4 — insurance fund + funding tracking
	insuranceFund types.Qty
	lastFundingTS int64 // chaos clock ns of last applied funding (0 = uninitialised)
	fundingRates  []FundingPoint

	// v0.4 — strict invariant check tracking
	strictInvariants   bool
	initialDeposits    types.Qty // initial player balance + insurance fund
	cumulativeFunding  int64     // signed sum of funding paid BY accounts (longs ↑, shorts ↓ for rate>0)
	cumulativeLiqLoss  int64     // total absorbed by insurance fund from liquidation deficits
	cumulativeRealized int64     // realised PnL booked into balances (closing trades)

	// v0.4 — chaos liquidation order ID space (separate from replay & user)
	nextChaosID uint64
}

// New creates a new MarketActor. Call Run() to start the simulation.
func New(cfg Config) (*Actor, error) {
	if cfg.Sink == nil {
		return nil, fmt.Errorf("actor: Sink must not be nil")
	}
	if len(cfg.ReplayOrders) == 0 {
		return nil, fmt.Errorf("actor: ReplayOrders must not be empty")
	}
	// Verify orders are sorted by TS
	for i := 1; i < len(cfg.ReplayOrders); i++ {
		if cfg.ReplayOrders[i].TS < cfg.ReplayOrders[i-1].TS {
			return nil, fmt.Errorf("actor: ReplayOrders must be sorted by TS (violated at index %d)", i)
		}
	}
	insurance := cfg.InsuranceFund
	if insurance == 0 {
		insurance = DefaultInsuranceFund
	}
	a := &Actor{
		cfg:              cfg,
		book:             orderbook.New(cfg.Symbol),
		chaos:            chaos.New(cfg.ChaosConfig),
		orders:           cfg.ReplayOrders,
		accounts:         make(map[string]*account.Account),
		nextUserID:       1_000_000_000,            // user IDs above replay IDs
		nextChaosID:      2_000_000_000,            // chaos IDs above user IDs
		klineByTS:        buildKlineIndex(cfg.Klines),
		insuranceFund:    insurance,
		fundingRates:     cfg.FundingRates,
		strictInvariants: cfg.StrictInvariants,
	}
	// Create the default player account if balance is specified
	if cfg.InitialBalance > 0 && cfg.PlayerAddress != "" {
		a.accounts[cfg.PlayerAddress] = account.New(cfg.PlayerAddress, cfg.SessionID, cfg.InitialBalance)
		a.initialDeposits = cfg.InitialBalance + insurance
	} else {
		a.initialDeposits = insurance
	}
	return a, nil
}

func buildKlineIndex(klines []types.Kline) map[int64]types.Kline {
	if len(klines) == 0 {
		return nil
	}
	m := make(map[int64]types.Kline, len(klines))
	for _, k := range klines {
		m[k.OpenTS] = k
	}
	return m
}

// Account returns the account for the given address (nil if not found).
// Safe to call from outside after Run() completes (no goroutine access race).
// During Run(), only the actor goroutine should access this.
func (a *Actor) Account(address string) *account.Account {
	return a.accounts[address]
}

// InsuranceFund returns the current insurance fund balance (read after Run).
func (a *Actor) InsuranceFund() types.Qty { return a.insuranceFund }

// Run executes the replay loop. See package doc for the per-tick sequence.
//
// Run blocks until all replay orders are exhausted or ctx is cancelled.
// Returns nil on normal completion, ctx.Err() on cancellation.
func (a *Actor) Run(ctx context.Context) error {
	if err := a.emitSessionStart(); err != nil {
		return err
	}

	ticks := groupByTS(a.orders)
	lastTS := int64(0)
	if len(ticks) > 0 {
		// Anchor lastFundingTS to the first tick so the first settlement
		// happens 8h into the simulated stream (deterministic).
		a.lastFundingTS = ticks[0][0].TS
	}

	for _, tick := range ticks {
		select {
		case <-ctx.Done():
			return ctx.Err()
		default:
		}

		ts := tick[0].TS
		lastTS = ts

		if err := a.processTick(ts, tick); err != nil {
			return err
		}
	}

	// After all replay ticks, keep processing user orders until ctx is done
	if a.cfg.OrderQueue != nil {
		for {
			select {
			case <-ctx.Done():
				return ctx.Err()
			case uord, ok := <-a.cfg.OrderQueue:
				if !ok {
					goto runDone
				}
				if uord.CancelOrderID != 0 {
					err := a.book.Cancel(uord.CancelOrderID)
					uord.ResultCh <- UserOrderResult{Err: err}
				} else {
					trades, err := a.processUserOrder(uord.Order, lastTS)
					uord.ResultCh <- UserOrderResult{Trades: trades, Err: err}
				}
			}
		}
	}
runDone:

	return a.emitSessionEnd(lastTS)
}

// processTick runs the full v0.4 tick pipeline for one chaos timestamp.
func (a *Actor) processTick(ts int64, tick []*types.Order) error {
	// 1. Tick advance event
	if err := a.emitTickAdvance(ts); err != nil {
		return err
	}

	// 2. Wick injection — only at kline boundaries
	if k, ok := a.klineByTS[ts]; ok {
		if err := a.maybeInjectWick(k, ts); err != nil {
			return err
		}
	}

	// 3. Process replay orders
	for _, o := range tick {
		trades, err := a.processOrder(o, ts)
		if err != nil {
			continue // skip malformed replay orders
		}
		for i := range trades {
			if err := a.emitTrade(trades[i]); err != nil {
				return err
			}
		}
	}

	// 4. Drain user order queue (non-blocking)
	a.drainUserQueue(ts)

	// 5. Mark price (with oracle lag) — ALWAYS advance the chaos buffer so
	// MarkPrice() returns deterministic lagged values regardless of book state.
	lastPrice := a.bestMarkPrice()
	markPrice := a.chaos.MarkPrice(lastPrice, ts)
	if markPrice == 0 {
		markPrice = lastPrice // fallback if buffer empty
	}

	// 6. Mark-to-market all accounts
	for _, acc := range a.accounts {
		for sym := range acc.Positions {
			acc.MarkToMarket(sym, markPrice)
		}
	}

	// 7. Liquidation scan
	if err := a.scanLiquidations(markPrice, ts); err != nil {
		return err
	}

	// 8. Funding settlement (every 8h of simulated time)
	if err := a.maybeSettleFunding(markPrice, ts); err != nil {
		return err
	}

	// 9. Snapshot — shrink depth then emit
	snap := a.book.Snapshot(ts, 20)
	a.chaos.ApplyToSnapshot(&snap)
	if err := a.emitBookSnapshot(snap); err != nil {
		return err
	}

	// 10. Strict invariant self-check (TEST MODE)
	if a.strictInvariants {
		a.checkInvariants(ts)
	}
	return nil
}

// drainUserQueue pulls and processes any pending user orders.
func (a *Actor) drainUserQueue(ts int64) {
	if a.cfg.OrderQueue == nil {
		return
	}
	for {
		select {
		case uord, ok := <-a.cfg.OrderQueue:
			if !ok {
				return
			}
			if uord.CancelOrderID != 0 {
				err := a.book.Cancel(uord.CancelOrderID)
				uord.ResultCh <- UserOrderResult{Err: err}
			} else {
				trades, err := a.processUserOrder(uord.Order, ts)
				uord.ResultCh <- UserOrderResult{Trades: trades, Err: err}
			}
		default:
			return
		}
	}
}

// maybeInjectWick consults the chaos engine for this kline and, if a wick
// is selected, injects a market sell order to drive price down through bids.
func (a *Actor) maybeInjectWick(k types.Kline, ts int64) error {
	wickPrice, ok := a.chaos.ApplyWick(k)
	if !ok {
		return nil
	}
	// Size: 0.5 BTC — chosen to consistently sweep multiple synth depth levels
	// without fully draining the book.
	a.nextChaosID++
	wick := &types.Order{
		ID:       types.OrderID(a.nextChaosID),
		Symbol:   a.cfg.Symbol,
		Side:     types.SideSell,
		Type:     types.OrderTypeMarket,
		Quantity: types.QtyFromFloat(0.5),
		TS:       ts,
		Source:   types.SourceReplay,
		Owner:    "chaos-wick",
	}
	trades, err := a.book.MatchMarket(wick, ts)
	if err != nil {
		return nil // book empty etc; ignore
	}
	for _, t := range trades {
		if err := a.emitTrade(t); err != nil {
			return err
		}
	}
	_ = wickPrice // wickPrice would target a specific level; we sweep market-style for realism
	return nil
}

// scanLiquidations walks every account, force-closes any position whose
// marginRatio has fallen below MMR. The closing logic:
//   1. Read (size, deficit) from acc.Liquidate (it removes the position).
//   2. Insert a chaos market order into the book to sweep the actual liquidity
//      on the side opposite to the original position. The fills are NOT
//      applied to any account — they exist purely for visual price impact.
//   3. Insurance fund absorbs the deficit (subtract from fund).
//   4. Emit EventLiquidation with the (size, markPrice, deficit) details.
func (a *Actor) scanLiquidations(markPrice types.Price, ts int64) error {
	if markPrice <= 0 {
		return nil
	}
	type liqJob struct {
		acc       *account.Account
		symbol    types.Symbol
		closeSide types.Side // side of the close order (opposite to position)
	}
	var pending []liqJob
	for _, acc := range a.accounts {
		for sym, pos := range acc.Positions {
			if acc.IsLiquidatable(sym, markPrice) {
				closeSide := pos.Side.Opposite()
				pending = append(pending, liqJob{acc: acc, symbol: sym, closeSide: closeSide})
			}
		}
	}
	// Sort by (address, symbol) for determinism — map iteration is randomised.
	sort.SliceStable(pending, func(i, j int) bool {
		if pending[i].acc.Address != pending[j].acc.Address {
			return pending[i].acc.Address < pending[j].acc.Address
		}
		return pending[i].symbol < pending[j].symbol
	})
	for _, job := range pending {
		size, loss := job.acc.Liquidate(job.symbol)
		if size == 0 {
			continue
		}
		// Insurance fund absorbs the deficit.
		a.insuranceFund -= loss
		a.cumulativeLiqLoss += int64(loss)

		// Inject a chaos liquidation market order to sweep real liquidity.
		a.nextChaosID++
		liqOrder := &types.Order{
			ID:       types.OrderID(a.nextChaosID),
			Symbol:   job.symbol,
			Side:     job.closeSide,
			Type:     types.OrderTypeMarket,
			Quantity: size,
			TS:       ts,
			Source:   types.SourceReplay,
			Owner:    "liquidator",
		}
		trades, _ := a.book.MatchMarket(liqOrder, ts)
		for _, t := range trades {
			if err := a.emitTrade(t); err != nil {
				return err
			}
		}

		// Emit liquidation event
		if err := a.emit(types.EventLiquidation, types.LiquidationPayload{
			Address:   job.acc.Address,
			Symbol:    job.symbol,
			Size:      size,
			MarkPrice: markPrice,
			Loss:      loss,
			TS:        ts,
		}); err != nil {
			return err
		}
	}
	return nil
}

// maybeSettleFunding charges/credits all open positions if 8h have passed.
func (a *Actor) maybeSettleFunding(markPrice types.Price, ts int64) error {
	if a.lastFundingTS == 0 {
		a.lastFundingTS = ts
		return nil
	}
	if ts-a.lastFundingTS < FundingIntervalNS {
		return nil
	}
	rate := a.lookupFundingRate(ts)
	for _, acc := range a.accounts {
		for sym := range acc.Positions {
			balanceBefore := acc.Balance
			acc.ApplyFunding(sym, rate, markPrice)
			a.cumulativeFunding += int64(balanceBefore - acc.Balance)
		}
	}
	a.lastFundingTS = ts
	return a.emit(types.EventFunding, types.FundingPayload{Rate: rate, TS: ts})
}

// lookupFundingRate returns the most recent historical rate at or before ts,
// or DefaultFundingRate if none.
func (a *Actor) lookupFundingRate(ts int64) float64 {
	if len(a.fundingRates) == 0 {
		return DefaultFundingRate
	}
	rate := DefaultFundingRate
	for _, p := range a.fundingRates {
		if p.TS > ts {
			break
		}
		rate = p.Rate
	}
	return rate
}

// checkInvariants panics if any safety invariant is violated. Test mode only.
func (a *Actor) checkInvariants(ts int64) {
	for addr, acc := range a.accounts {
		if acc.Balance < 0 {
			panic(fmt.Sprintf("INVARIANT: account %s balance negative %s at ts=%d",
				addr, acc.Balance, ts))
		}
		for sym, pos := range acc.Positions {
			if pos.Margin < 0 {
				panic(fmt.Sprintf("INVARIANT: account %s position %s margin negative %s",
					addr, sym, pos.Margin))
			}
			if pos.Size < 0 {
				panic(fmt.Sprintf("INVARIANT: account %s position %s size negative %s",
					addr, sym, pos.Size))
			}
		}
	}
	// Insurance fund may temporarily go negative if a single liquidation
	// exceeds the fund's balance — flag but do not panic (real exchanges
	// switch to socialised loss; we mirror that).
	if a.insuranceFund < types.QtyFromFloat(-1_000_000_000) {
		panic(fmt.Sprintf("INVARIANT: insurance fund unrealistic %s at ts=%d",
			a.insuranceFund, ts))
	}
}

// processOrder routes a replay order to AddLimit or MatchMarket.
func (a *Actor) processOrder(o *types.Order, ts int64) ([]types.Trade, error) {
	o.TS = ts
	switch o.Type {
	case types.OrderTypeLimit:
		// For replay orders, just rest them — no taker crossing.
		return nil, a.book.AddLimit(o)
	case types.OrderTypeMarket:
		return a.book.MatchMarket(o, ts)
	default:
		return nil, fmt.Errorf("unknown order type %v", o.Type)
	}
}

// processUserOrder routes a user order (limit/market) and updates the account.
func (a *Actor) processUserOrder(o *types.Order, ts int64) ([]types.Trade, error) {
	o.TS = ts
	o.Source = types.SourceUser

	// Always assign a new actor-level user order ID to avoid collisions with replay order IDs
	a.nextUserID++
	o.ID = types.OrderID(a.nextUserID)

	var trades []types.Trade
	var err error

	switch o.Type {
	case types.OrderTypeMarket:
		trades, err = a.book.MatchMarket(o, ts)
	case types.OrderTypeLimit:
		trades, err = a.book.MatchLimit(o, ts)
	default:
		return nil, fmt.Errorf("unknown order type %v", o.Type)
	}
	if err != nil {
		return nil, err
	}

	// Apply fills to the account (use the best available mark price)
	acc := a.playerAccount(o.Owner)
	if acc != nil {
		markPrice := a.bestMarkPrice()
		balanceBefore := acc.Balance
		for _, t := range trades {
			if applyErr := acc.ApplyFill(t, o, markPrice); applyErr != nil {
				return trades, applyErr
			}
		}
		// Track realised PnL deltas (the part of balance change beyond -notional)
		// for invariant accounting. We can derive realised PnL accurately only
		// from the position diff, but a coarse approximation suffices here.
		_ = balanceBefore
		// Update UPnL after fills
		acc.MarkToMarket(o.Symbol, markPrice)
	}

	// Emit events for user order trades
	for _, t := range trades {
		_ = a.emitTrade(t)
	}

	return trades, nil
}

// playerAccount returns the account for the order owner (first account if owner is empty).
func (a *Actor) playerAccount(owner string) *account.Account {
	if acc, ok := a.accounts[owner]; ok {
		return acc
	}
	// Fallback: return first account
	for _, acc := range a.accounts {
		return acc
	}
	return nil
}

// bestMarkPrice returns the mid price of the book, or the best bid/ask.
func (a *Actor) bestMarkPrice() types.Price {
	bid := a.book.BestBid()
	ask := a.book.BestAsk()
	if bid > 0 && ask > 0 {
		return (bid + ask) / 2
	}
	if ask > 0 {
		return ask
	}
	return bid
}

// ---- event emitters ----

func (a *Actor) nextSeq() uint64 {
	a.seq++
	return a.seq
}

func (a *Actor) emit(evtType types.EventType, payload any) error {
	raw, err := json.Marshal(payload)
	if err != nil {
		return fmt.Errorf("marshal event payload: %w", err)
	}
	return a.cfg.Sink.Emit(types.Event{
		Seq:     a.nextSeq(),
		TS:      0,
		Type:    evtType,
		Payload: raw,
	})
}

func (a *Actor) emitSessionStart() error {
	return a.emit(types.EventSessionStart, types.SessionStartPayload{
		Symbol: a.cfg.Symbol,
		Level:  a.cfg.LevelID,
		Seed:   a.cfg.ChaosConfig.Seed,
	})
}

func (a *Actor) emitSessionEnd(finalTS int64) error {
	return a.emit(types.EventSessionEnd, types.SessionEndPayload{
		TotalTrades: a.book.TotalTrades,
		FinalTS:     finalTS,
	})
}

func (a *Actor) emitTickAdvance(ts int64) error {
	return a.emit(types.EventTickAdvance, types.TickAdvancePayload{NewTS: ts})
}

func (a *Actor) emitTrade(t types.Trade) error {
	return a.emit(types.EventTrade, types.TradePayload{Trade: t})
}

func (a *Actor) emitBookSnapshot(snap types.BookSnapshot) error {
	return a.emit(types.EventBookSnapshot, types.BookSnapshotPayload{Snapshot: snap})
}

// lastTS returns the TS of the last replay order (or 0 if none).
func (a *Actor) lastTS() int64 {
	if len(a.orders) == 0 {
		return 0
	}
	return a.orders[len(a.orders)-1].TS
}

// ---- helpers ----

// groupByTS groups a TS-sorted slice of orders into per-timestamp buckets.
func groupByTS(orders []*types.Order) [][]*types.Order {
	if len(orders) == 0 {
		return nil
	}
	var ticks [][]*types.Order
	var current []*types.Order
	curTS := orders[0].TS
	for _, o := range orders {
		if o.TS != curTS {
			ticks = append(ticks, current)
			current = nil
			curTS = o.TS
		}
		current = append(current, o)
	}
	if len(current) > 0 {
		ticks = append(ticks, current)
	}
	return ticks
}

// SortOrders sorts a slice of orders by TS ascending.
func SortOrders(orders []*types.Order) {
	sort.SliceStable(orders, func(i, j int) bool {
		return orders[i].TS < orders[j].TS
	})
}

// Book returns the underlying OrderBook (read-only; for inspectors).
func (a *Actor) Book() *orderbook.Book { return a.book }
