// Package actor implements the MarketActor — the single goroutine that owns
// one OrderBook and drives the chaos+replay pipeline.
//
// Design invariant (CRITICAL):
//
//	The MarketActor MUST be the ONLY writer to its OrderBook.
//	All external callers (CLI, HTTP handlers) submit orders via the OrderQueue
//	channel. The actor processes them on its goroutine, so no mutex is needed
//	inside OrderBook or Account.
//
// Event log guarantee:
//
//	Every event emitted is appended to the EventSink in sequence-number order.
//	Two runs with identical (seed, replay data) MUST produce byte-identical
//	output to the EventSink. This is tested by the determinism regression test.
package actor

import (
	"context"
	"encoding/json"
	"fmt"
	"sort"

	"github.com/sandswind/perpCS/internal/account"
	"github.com/sandswind/perpCS/internal/chaos"
	"github.com/sandswind/perpCS/internal/orderbook"
	"github.com/sandswind/perpCS/internal/types"
)

// EventSink receives every event produced by the actor.
type EventSink interface {
	Emit(e types.Event) error
}

// UserOrder is a user-submitted order envelope.
// The caller must send this into Config.OrderQueue and wait on ResultCh.
// For a cancel operation, set CancelOrderID to the target order ID and
// leave Order nil (or set it to a zero-value Order).
type UserOrder struct {
	Order         *types.Order
	CancelOrderID types.OrderID  // non-zero → cancel this order instead of placing
	ResultCh      chan UserOrderResult // buffered(1); caller blocks on receive
}

// UserOrderResult is sent back on UserOrder.ResultCh after the actor processes it.
type UserOrderResult struct {
	Trades []types.Trade
	Err    error
}

// Config holds the parameters for one MarketActor session.
type Config struct {
	Symbol      types.Symbol
	SessionID   string
	LevelID     string // e.g. "D-312-BTC"
	ChaosConfig chaos.Config
	// ReplayOrders is the pre-sorted slice of orders to inject, generated by
	// provider.KlinesToSynthOrders. Must be sorted by TS ascending.
	ReplayOrders []*types.Order
	// Sink receives every event. Must not be nil.
	Sink EventSink
	// OrderQueue delivers user orders to the actor goroutine.
	// If nil, the actor runs in replay-only mode (no user interaction).
	OrderQueue <-chan *UserOrder
	// InitialBalance is the player's starting balance (1e8 USDR scaled).
	// If 0 the account is not created (replay-only mode).
	InitialBalance types.Qty
	// PlayerAddress is used as the account owner ID.
	PlayerAddress string
}

// Actor is a single-goroutine market actor for one symbol.
// Run() drives the full replay loop and blocks until completion or ctx done.
type Actor struct {
	cfg         Config
	book        *orderbook.Book
	chaos       *chaos.Engine
	seq         uint64
	orders      []*types.Order // replay orders
	accounts    map[string]*account.Account
	nextUserID  uint64 // monotonic user order ID counter (separate from book counter)
}

// New creates a new MarketActor. Call Run() to start the simulation.
func New(cfg Config) (*Actor, error) {
	if cfg.Sink == nil {
		return nil, fmt.Errorf("actor: Sink must not be nil")
	}
	if len(cfg.ReplayOrders) == 0 {
		return nil, fmt.Errorf("actor: ReplayOrders must not be empty")
	}
	// Verify orders are sorted by TS
	for i := 1; i < len(cfg.ReplayOrders); i++ {
		if cfg.ReplayOrders[i].TS < cfg.ReplayOrders[i-1].TS {
			return nil, fmt.Errorf("actor: ReplayOrders must be sorted by TS (violated at index %d)", i)
		}
	}
	a := &Actor{
		cfg:        cfg,
		book:       orderbook.New(cfg.Symbol),
		chaos:      chaos.New(cfg.ChaosConfig),
		orders:     cfg.ReplayOrders,
		accounts:   make(map[string]*account.Account),
		nextUserID: 1_000_000_000, // start user IDs far above replay IDs
	}
	// Create the default player account if balance is specified
	if cfg.InitialBalance > 0 && cfg.PlayerAddress != "" {
		a.accounts[cfg.PlayerAddress] = account.New(cfg.PlayerAddress, cfg.SessionID, cfg.InitialBalance)
	}
	return a, nil
}

// Account returns the account for the given address (nil if not found).
// Safe to call from outside after Run() completes (no goroutine access race).
// During Run(), only the actor goroutine should access this.
func (a *Actor) Account(address string) *account.Account {
	return a.accounts[address]
}

// Run executes the replay loop.
//
// For each unique timestamp in the replay order stream:
//  1. Emit TickAdvance event
//  2. Inject all orders with that timestamp into the OrderBook
//  3. After each match, emit Trade events
//  4. Drain the user order queue (non-blocking)
//  5. Emit BookSnapshot event
//
// Run blocks until all replay orders are exhausted or ctx is cancelled.
// Returns nil on normal completion, ctx.Err() on cancellation.
func (a *Actor) Run(ctx context.Context) error {
	if err := a.emitSessionStart(); err != nil {
		return err
	}

	ticks := groupByTS(a.orders)
	lastTS := int64(0)

	for _, tick := range ticks {
		select {
		case <-ctx.Done():
			return ctx.Err()
		default:
		}

		ts := tick[0].TS
		lastTS = ts

		// 1. Tick advance
		if err := a.emitTickAdvance(ts); err != nil {
			return err
		}

		// 2+3. Process replay orders in this tick
		for _, o := range tick {
			trades, err := a.processOrder(o, ts)
			if err != nil {
				continue // skip malformed replay orders
			}
			for i := range trades {
				if err := a.emitTrade(trades[i]); err != nil {
					return err
				}
			}
		}

		// 4. Drain user order queue (non-blocking)
	drainLoop:
		for {
			select {
			case uord, ok := <-a.cfg.OrderQueue:
				if !ok {
					break drainLoop
				}
				if uord.CancelOrderID != 0 {
					err := a.book.Cancel(uord.CancelOrderID)
					uord.ResultCh <- UserOrderResult{Err: err}
				} else {
					trades, err := a.processUserOrder(uord.Order, ts)
					uord.ResultCh <- UserOrderResult{Trades: trades, Err: err}
				}
			default:
				break drainLoop
			}
		}

		// 5. Snapshot every tick
		snap := a.book.Snapshot(ts, 20)
		if err := a.emitBookSnapshot(snap); err != nil {
			return err
		}
	}

	// After all replay ticks, keep processing user orders until ctx is done
	// (the server stays responsive after replay completes)
	if a.cfg.OrderQueue != nil {
		for {
			select {
			case <-ctx.Done():
				return ctx.Err()
			case uord, ok := <-a.cfg.OrderQueue:
				if !ok {
					goto runDone
				}
				if uord.CancelOrderID != 0 {
					err := a.book.Cancel(uord.CancelOrderID)
					uord.ResultCh <- UserOrderResult{Err: err}
				} else {
					trades, err := a.processUserOrder(uord.Order, lastTS)
					uord.ResultCh <- UserOrderResult{Trades: trades, Err: err}
				}
			}
		}
	}
runDone:

	return a.emitSessionEnd(lastTS)
}

// processOrder routes a replay order to AddLimit or MatchMarket.
func (a *Actor) processOrder(o *types.Order, ts int64) ([]types.Trade, error) {
	o.TS = ts
	switch o.Type {
	case types.OrderTypeLimit:
		// For replay orders, just rest them — no taker crossing.
		return nil, a.book.AddLimit(o)
	case types.OrderTypeMarket:
		return a.book.MatchMarket(o, ts)
	default:
		return nil, fmt.Errorf("unknown order type %v", o.Type)
	}
}

// processUserOrder routes a user order (limit/market) and updates the account.
func (a *Actor) processUserOrder(o *types.Order, ts int64) ([]types.Trade, error) {
	o.TS = ts
	o.Source = types.SourceUser

	// Always assign a new actor-level user order ID to avoid collisions with replay order IDs
	a.nextUserID++
	o.ID = types.OrderID(a.nextUserID)

	var trades []types.Trade
	var err error

	switch o.Type {
	case types.OrderTypeMarket:
		trades, err = a.book.MatchMarket(o, ts)
	case types.OrderTypeLimit:
		trades, err = a.book.MatchLimit(o, ts)
	default:
		return nil, fmt.Errorf("unknown order type %v", o.Type)
	}
	if err != nil {
		return nil, err
	}

	// Apply fills to the account (use the best available mark price)
	acc := a.playerAccount(o.Owner)
	if acc != nil {
		markPrice := a.bestMarkPrice()
		for _, t := range trades {
			if applyErr := acc.ApplyFill(t, o, markPrice); applyErr != nil {
				// Return error but also return whatever trades matched
				return trades, applyErr
			}
		}
		// Update UPnL after fills
		acc.MarkToMarket(o.Symbol, markPrice)
	}

	// Emit events for user order trades
	for _, t := range trades {
		_ = a.emitTrade(t)
	}

	return trades, nil
}

// playerAccount returns the account for the order owner (first account if owner is empty).
func (a *Actor) playerAccount(owner string) *account.Account {
	if acc, ok := a.accounts[owner]; ok {
		return acc
	}
	// Fallback: return first account
	for _, acc := range a.accounts {
		return acc
	}
	return nil
}

// bestMarkPrice returns the mid price of the book, or the best bid/ask.
func (a *Actor) bestMarkPrice() types.Price {
	bid := a.book.BestBid()
	ask := a.book.BestAsk()
	if bid > 0 && ask > 0 {
		return (bid + ask) / 2
	}
	if ask > 0 {
		return ask
	}
	return bid
}

// ---- event emitters ----

func (a *Actor) nextSeq() uint64 {
	a.seq++
	return a.seq
}

func (a *Actor) emit(evtType types.EventType, payload any) error {
	raw, err := json.Marshal(payload)
	if err != nil {
		return fmt.Errorf("marshal event payload: %w", err)
	}
	return a.cfg.Sink.Emit(types.Event{
		Seq:     a.nextSeq(),
		TS:      0,
		Type:    evtType,
		Payload: raw,
	})
}

func (a *Actor) emitSessionStart() error {
	return a.emit(types.EventSessionStart, types.SessionStartPayload{
		Symbol: a.cfg.Symbol,
		Level:  a.cfg.LevelID,
		Seed:   a.cfg.ChaosConfig.Seed,
	})
}

func (a *Actor) emitSessionEnd(finalTS int64) error {
	return a.emit(types.EventSessionEnd, types.SessionEndPayload{
		TotalTrades: a.book.TotalTrades,
		FinalTS:     finalTS,
	})
}

func (a *Actor) emitTickAdvance(ts int64) error {
	return a.emit(types.EventTickAdvance, types.TickAdvancePayload{NewTS: ts})
}

func (a *Actor) emitTrade(t types.Trade) error {
	return a.emit(types.EventTrade, types.TradePayload{Trade: t})
}

func (a *Actor) emitBookSnapshot(snap types.BookSnapshot) error {
	return a.emit(types.EventBookSnapshot, types.BookSnapshotPayload{Snapshot: snap})
}

// lastTS returns the TS of the last replay order (or 0 if none).
func (a *Actor) lastTS() int64 {
	if len(a.orders) == 0 {
		return 0
	}
	return a.orders[len(a.orders)-1].TS
}

// ---- helpers ----

// groupByTS groups a TS-sorted slice of orders into per-timestamp buckets.
func groupByTS(orders []*types.Order) [][]*types.Order {
	if len(orders) == 0 {
		return nil
	}
	var ticks [][]*types.Order
	var current []*types.Order
	curTS := orders[0].TS
	for _, o := range orders {
		if o.TS != curTS {
			ticks = append(ticks, current)
			current = nil
			curTS = o.TS
		}
		current = append(current, o)
	}
	if len(current) > 0 {
		ticks = append(ticks, current)
	}
	return ticks
}

// SortOrders sorts a slice of orders by TS ascending.
func SortOrders(orders []*types.Order) {
	sort.SliceStable(orders, func(i, j int) bool {
		return orders[i].TS < orders[j].TS
	})
}

// Book returns the underlying OrderBook (read-only; for inspectors).
func (a *Actor) Book() *orderbook.Book { return a.book }
