// Package actor implements the MarketActor — the single goroutine that owns
// one OrderBook and drives the chaos+replay pipeline.
//
// Design invariant (CRITICAL):
//   The MarketActor MUST be the ONLY writer to its OrderBook.
//   All external callers (CLI, HTTP handlers in v0.2+) submit orders via
//   the OrderQueue channel. The actor processes them on its goroutine, so
//   no mutex is needed inside OrderBook.
//
// Event log guarantee:
//   Every event emitted is appended to the EventSink in sequence-number order.
//   Two runs with identical (seed, replay data) MUST produce byte-identical
//   output to the EventSink. This is tested by the determinism regression test.
package actor

import (
	"context"
	"encoding/json"
	"fmt"
	"sort"

	"github.com/sandswind/perpCS/internal/chaos"
	"github.com/sandswind/perpCS/internal/orderbook"
	"github.com/sandswind/perpCS/internal/types"
)

// EventSink receives every event produced by the actor.
// The only implementation in v0.1 is a JSONL file writer.
// In v0.3+ a channel fan-out forwards to WS subscribers.
type EventSink interface {
	Emit(e types.Event) error
}

// Config holds the parameters for one MarketActor session.
type Config struct {
	Symbol      types.Symbol
	SessionID   string
	LevelID     string     // e.g. "D-312-BTC"
	ChaosConfig chaos.Config
	// ReplayOrders is the pre-sorted slice of orders to inject, generated by
	// provider.KlinesToSynthOrders. Must be sorted by TS ascending.
	ReplayOrders []*types.Order
	// Sink receives every event. Must not be nil.
	Sink EventSink
}

// Actor is a single-goroutine market actor for one symbol.
// Run() drives the full replay loop and blocks until completion or ctx done.
type Actor struct {
	cfg    Config
	book   *orderbook.Book
	chaos  *chaos.Engine
	seq    uint64
	orders []*types.Order // replay orders, index cursor
	cursor int
}

// New creates a new MarketActor. Call Run() to start the simulation.
func New(cfg Config) (*Actor, error) {
	if cfg.Sink == nil {
		return nil, fmt.Errorf("actor: Sink must not be nil")
	}
	if len(cfg.ReplayOrders) == 0 {
		return nil, fmt.Errorf("actor: ReplayOrders must not be empty")
	}
	// Verify orders are sorted by TS
	for i := 1; i < len(cfg.ReplayOrders); i++ {
		if cfg.ReplayOrders[i].TS < cfg.ReplayOrders[i-1].TS {
			return nil, fmt.Errorf("actor: ReplayOrders must be sorted by TS (violated at index %d)", i)
		}
	}
	return &Actor{
		cfg:    cfg,
		book:   orderbook.New(cfg.Symbol),
		chaos:  chaos.New(cfg.ChaosConfig),
		orders: cfg.ReplayOrders,
	}, nil
}

// Run executes the replay loop.
//
// For each unique timestamp in the replay order stream:
//  1. Emit TickAdvance event
//  2. Inject all orders with that timestamp into the OrderBook
//     (limits are rested; markets are matched immediately)
//  3. After each match, emit Trade events
//  4. Emit BookSnapshot event
//
// Run blocks until all replay orders are exhausted or ctx is cancelled.
// Returns nil on normal completion, ctx.Err() on cancellation.
func (a *Actor) Run(ctx context.Context) error {
	if err := a.emitSessionStart(); err != nil {
		return err
	}

	// Group orders by timestamp into ticks
	ticks := groupByTS(a.orders)

	for _, tick := range ticks {
		if ctx.Err() != nil {
			return ctx.Err()
		}
		ts := tick[0].TS

		// 1. Tick advance
		if err := a.emitTickAdvance(ts); err != nil {
			return err
		}

		// 2+3. Process orders in this tick
		for _, o := range tick {
			trades, err := a.processOrder(o, ts)
			if err != nil {
				// Non-fatal: skip malformed replay orders
				continue
			}
			for i := range trades {
				if err := a.emitTrade(trades[i]); err != nil {
					return err
				}
			}
		}

		// 4. Snapshot every tick
		snap := a.book.Snapshot(ts, 20)
		if err := a.emitBookSnapshot(snap); err != nil {
			return err
		}
	}

	return a.emitSessionEnd(a.lastTS())
}

// processOrder routes the order to AddLimit or MatchMarket.
func (a *Actor) processOrder(o *types.Order, ts int64) ([]types.Trade, error) {
	o.TS = ts
	switch o.Type {
	case types.OrderTypeLimit:
		// For replay orders, just rest them — no taker crossing.
		// (User orders in v0.2+ use MatchLimit.)
		return nil, a.book.AddLimit(o)
	case types.OrderTypeMarket:
		return a.book.MatchMarket(o, ts)
	default:
		return nil, fmt.Errorf("unknown order type %v", o.Type)
	}
}

// ---- event emitters ----

func (a *Actor) nextSeq() uint64 {
	a.seq++
	return a.seq
}

func (a *Actor) emit(evtType types.EventType, payload any) error {
	raw, err := json.Marshal(payload)
	if err != nil {
		return fmt.Errorf("marshal event payload: %w", err)
	}
	return a.cfg.Sink.Emit(types.Event{
		Seq:     a.nextSeq(),
		TS:      0, // caller sets if needed; for audit we use payload.TS
		Type:    evtType,
		Payload: raw,
	})
}

func (a *Actor) emitSessionStart() error {
	return a.emit(types.EventSessionStart, types.SessionStartPayload{
		Symbol: a.cfg.Symbol,
		Level:  a.cfg.LevelID,
		Seed:   a.cfg.ChaosConfig.Seed,
	})
}

func (a *Actor) emitSessionEnd(finalTS int64) error {
	return a.emit(types.EventSessionEnd, types.SessionEndPayload{
		TotalTrades: a.book.TotalTrades,
		FinalTS:     finalTS,
	})
}

func (a *Actor) emitTickAdvance(ts int64) error {
	return a.emit(types.EventTickAdvance, types.TickAdvancePayload{NewTS: ts})
}

func (a *Actor) emitTrade(t types.Trade) error {
	return a.emit(types.EventTrade, types.TradePayload{Trade: t})
}

func (a *Actor) emitBookSnapshot(snap types.BookSnapshot) error {
	return a.emit(types.EventBookSnapshot, types.BookSnapshotPayload{Snapshot: snap})
}

// lastTS returns the TS of the last replay order (or 0 if none).
func (a *Actor) lastTS() int64 {
	if len(a.orders) == 0 {
		return 0
	}
	return a.orders[len(a.orders)-1].TS
}

// ---- helpers ----

// groupByTS groups a TS-sorted slice of orders into per-timestamp buckets.
// Orders with the same TS are processed together as one "tick".
func groupByTS(orders []*types.Order) [][]*types.Order {
	if len(orders) == 0 {
		return nil
	}
	// orders is already sorted by TS (validated in New)
	var ticks [][]*types.Order
	var current []*types.Order
	curTS := orders[0].TS
	for _, o := range orders {
		if o.TS != curTS {
			ticks = append(ticks, current)
			current = nil
			curTS = o.TS
		}
		current = append(current, o)
	}
	if len(current) > 0 {
		ticks = append(ticks, current)
	}
	return ticks
}

// SortOrders sorts a slice of orders by TS ascending (stable sort preserves
// the original order for equal timestamps, maintaining FIFO within a tick).
func SortOrders(orders []*types.Order) {
	sort.SliceStable(orders, func(i, j int) bool {
		return orders[i].TS < orders[j].TS
	})
}

// Book returns the underlying OrderBook (read-only; for inspectors).
func (a *Actor) Book() *orderbook.Book { return a.book }
